### ISSUE TITLE
Cannot handle source

### ISSUE THREAD

**Issue by pernillekle** [fivetran/dbt-language-server#429]
dbt wizard complains when using {{ source('dataset','model') }}, though it compiles correctly when using 'Show query preview'

![image](https://user-images.githubusercontent.com/100143873/192266474-6cb06fe2-720a-48fd-9665-ca66738c8fb9.png)

**Comment by pgrivachev** [comment]
Hi @pernillekle,

Could you please clarify what the error are you seeing in the Problems tab for this model?
![image](https://user-images.githubusercontent.com/3650304/192617148-3322dc4f-d730-4ca3-af6d-21e27f16859f.png)

Can you also attach logs from output tab after selecting dbt Wizard in the right select box?

**Comment by assafshayhaimhibob** [comment]
Hi, Same error here
<img width="616" alt="Screenshot 2022-12-24 at 16 53 00" src="https://user-images.githubusercontent.com/110016980/209441489-86f715c0-9c56-4c8f-a062-55ec76245af2.png">
<img width="462" alt="Screenshot 2022-12-24 at 16 53 18" src="https://user-images.githubusercontent.com/110016980/209441496-82198fad-f6ca-4f30-83d9-8625476d042a.png">

How to fix that?

**Comment by pgrivachev** [comment]
Hi @assafshayhaimhibob. Do you get such error for any model of your project? How big is your dbt project?

As a workaround you can try to change compiler to `dbt` instead of `dbt-rpc`. You can find this setting in Preferences -> Settings -> Extensions -> Wizard for dbt Core (TM) -> Wizard For Dbt Core(TM): Dbt Compiler.
![image](https://user-images.githubusercontent.com/3650304/209567605-35ca08ba-f722-4ac8-87f3-24c5cee44f02.png)

**Comment by assafshayhaimhibob** [comment]
Hi @pgrivachev, I only have several sources in my project and same error for all of them. 
The workaround seems to be working.
Thank you.
